Setup daily firebase distribution

diff --git a/.github/workflows/firebase.yml b/.github/workflows/firebase.yml
--- a/.github/workflows/firebase.yml
+++ b/.github/workflows/firebase.yml
@@ -3,23 +3,69 @@ name: Daily Android Build for Firebase
 on:
   schedule:
     - cron: '0 9 * * *'   # 09:00 UTC
-
+  workflow_dispatch:
 jobs:
   android-build:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-java@v4
+      # ----------------- CHECKOUT -----------------
+      - name: Checkout develop
+        uses: actions/checkout@v4
+        with:
+          ref: develop
+          
+      # ----------------- SETUP JAVA -----------------
+      - name: Setup Java
+        uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 21
+
+      # ----------------- SET BUILD NAME -----------------
+      - name: Set BUILD_NAME
+        run: echo "BUILD_NAME=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV
+
+      # ----------------- DECODE KEYSTORE -----------------
       - name: Decode Keystore
-        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
-      - run: ./gradlew :composeApp:bundleRelease
-      - name: Upload Firebase
+        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > composeApp/keystore.jks
+
+      - name: Check Keystore exists
+        run: |
+          if [ ! -f composeApp/keystore.jks ]; then
+            echo "Keystore not found!"
+            exit 1
+          fi
+          ls -lh composeApp/keystore.jks
+
+      # ----------------- BUILD AAB -----------------
+      - name: Build AAB
+        env:
+          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
+          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
+          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
+          BUILD_NAME: ${{ env.BUILD_NAME }}
+          GITHUB_RUN_NUMBER: ${{ github.run_number }}
+        run: ./gradlew :composeApp:bundleRelease
+
+      # ----------------- CHECK AAB -----------------
+      - name: Check AAB exists
+        id: check-aab
+        run: |
+          AAB_PATH=$(find composeApp/build/outputs -name "*.aab")
+          echo "Found AAB at $AAB_PATH"
+          if [ ! -f "$AAB_PATH" ]; then
+            echo "ERROR: AAB not found!"
+            exit 1
+          fi
+          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_OUTPUT
+
+      # ----------------- UPLOAD TO FIREBASE -----------------
+      - name: Upload to Firebase
         uses: wzieba/Firebase-Distribution-Github-Action@v1
         with:
           appId: ${{ secrets.FIREBASE_APP_ID }}
           token: ${{ secrets.FIREBASE_TOKEN }}
-          groups: beta-testers
-          file: composeApp/build/outputs/bundle/release/app-release.aab
+          groups: alpha-testers
+          file: ${{ steps.check-aab.outputs.AAB_PATH }}
+          releaseNotes: "Build ${{ github.run_number }} - commit ${{ env.COMMIT_HASH }}"
